### ISSUE TITLE
Makefile Relative path locations

### ISSUE THREAD

**Issue by kj3moraes** [kj3moraes/further-testing-xmss#2]
This is only relevant to any of the branches where I have edited code. The Makefile variable _INC_FLAGS_ and _LD_FLAGS_ have the path specified as a relative path from my testing repository location to liboqs clone on my local machine. Please edit these paths to the appropriate liboqs clone location on your machines.

**Comment by ducnguyen-aq** [comment]
It built fine in my machine. Just need to install libOQS into the file system.
